customer = Customer.create!(first_name: 'Fake', last_name: 'Customer')
invoice = Invoice.create!(
  estimate_number: 123,
  invoice_total: 100,
  intake_date: Date.current.to_s,
  date_fulfilled: Date.current.to_s,
  customer: customer,
  notes: 'Generated by seed file',
  number: 1
)

technician = Technician.create(name: 'Fake Technician', skill_level: 'Maximum funk')
